### ISSUE TITLE
質問の格納、取り出し

### ISSUE THREAD

**Issue by toshi-pono** [22hack12spring/backend#15]
- [ ] 質問の格納
- [ ] 質問の取り出し

質問の取り出しはuuidからできるようにしたいね

**Comment by toshi-pono** [comment]
#7 を先にやらないとだめやね

**Comment by toshi-pono** [comment]
質問は、事前に生成しておいたものを使う方針に変更したので、必要なのは、
- `shop_id`,`number` の配列と、`search_id`を受け取って`questions`テーブルにデータを格納する関数
- `shops`から質問一覧を取り出す関数
- `uuid`から 質問に使った`shop`の配列を`shops`テーブルから取り出す関数

あたりですかね:eyes:

**Comment by toshi-pono** [comment]
> 質問は、事前に生成しておいたものを使う方針に変更したので

↑連絡遅れてすみません。この方針で行きたいと思います

**Comment by toshi-pono** [comment]
あー、shopsに入れる初期データないとテストしづらいですね……やばい！適当に生成できたらしてください
```python
"http://webservice.recruit.co.jp/hotpepper/gourmet/v1/?key={}&format=json&count=100&keyword={}".format(
    api_key, "品川")
```

**Comment by grkon03** [comment]
了解です〜

**Comment by toshi-pono** [comment]
↑ @grkon03 今少し手が空いているので、テストデータ兼本番データ作ってみます

**Comment by toshi-pono** [comment]
~~@grokon03 質問の取り出しを実装しますね~~:eyes: やめました
